import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Session } from "inspector";
import { SessionProvider } from "next-auth/react";
import TanStackQueryProvider from "@/context/TanStackQueryContext";
import ContextProvider from "@/context";
import Header from "@/components/header/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ContextProvider>
        <body className={inter.className}>
          <div className="bg-gray-900 min-h-screen">
            <div className="container mx-auto py-8 px-4">
              <div className="bg-gray-600 rounded-lg px-10 py-8">
                <Header />
              </div>
            </div>
            <div className="container mx-auto py-8 px-4">
              <div className="bg-gray-600 rounded-lg px-10 py-8">
                {children}
              </div>
            </div>
          </div>
        </body>
      </ContextProvider>
    </html>
  );
}
